import { Header } from '../../components/reusableComponent/header/header'
import { Footer } from '../../components/reusableComponent/footer/footer'
import '../_styles/globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { cookies } from 'next/headers';
import { ClientCookiesProvider } from '../../components/cookiesComponent/cookiesClient';
// import {isAuthenticated} from '../../services/authentication'
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}





export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // console.log(isAuthenticated(), 'authhh');

  return (
    <html lang="en">
      <body className={`${roboto.className} bodyClass`}>
        <ClientCookiesProvider value={cookies().getAll()}>
          <Header />
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          {children}
          <Footer />
        </ClientCookiesProvider>
      </body>
    </html>
  )
}
